apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /Users/hakkisagdic/Documents/GitHub/otokoc-demo/secrets.json
  - name: nestedSeparator
    value: ":"
