apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: payment-store
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: redisDB
    value: "5"
  - name: actorStateStore
    value: "false"
