apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: notification-store
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=localhost user=dapr password=dapr123 dbname=dapr_state port=5432 sslmode=disable"
  - name: tableName
    value: "notification_state"
